image: fedora:31

stages:
  - build

before_script:
  - dnf install -y meson ninja-build git gcc glib2-devel libsoup-devel libexif-devel libxml2-devel json-glib-devel libgcrypt-devel gtk3-devel gstreamer1-devel yelp-tools gettext libgcrypt-devel itstool desktop-file-utils libappstream-glib

build-frogr:
  stage: build
  script:
    - meson --prefix /usr _build .
    - cd _build
    - ninja
    - desktop-file-validate data/org.gnome.frogr.desktop
    - appstream-util validate data/org.gnome.frogr.appdata.xml
  except:
    - tags
  artifacts:
    when: on_failure
    name: "frogr-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"

build-frogr-no-header-bar:
  stage: build
  script:
    - meson --prefix /usr -Denable-header-bar=false _build .
    - cd _build
    - ninja
    - desktop-file-validate data/org.gnome.frogr.desktop
    - appstream-util validate data/org.gnome.frogr.appdata.xml
  except:
    - tags

build-frogr-no-video:
  stage: build
  script:
    - meson --prefix /usr -Denable-video=false _build .
    - cd _build
    - ninja
    - desktop-file-validate data/org.gnome.frogr.desktop
    - appstream-util validate data/org.gnome.frogr.appdata.xml
  except:
    - tags

dist-frogr:
  stage: build
  only:
    - tags
  script:
    - meson --prefix /usr --buildtype release -Denable-header-bar=true _build .
    - cd _build
    - ninja dist
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-dist/frogr-*.tar.xz"

